### PR TITLE
fix misread of KANJI

### PR DESCRIPTION
**Pull request by j-un**
It seems to misread of KANJI:ramen:

### CODE REVIEW

**Comment by hiroppy** [comment]
thx;)

**Comment by watilde** [comment]
@j-un Thanks for the contribution. Would you mind if I invite you to this org as a member?

**Comment by j-un** [comment]
@watilde Thank you, but I don't know anything about nodejs(also english too, SUKOSHIDAKE), is that ok?

**Comment by watilde** [comment]
@j-un That's totally fine since you've contribute d already! I sent you an invitation.
Hope you will be interested in Nose.js itself as well :)

**Comment by j-un** [comment]
Thanks!
I'll study Node.js at this opportunity.

**Pull request merged**
